projects:
  app:  
    schema : http://localhost:4466/
  database: 
    schema: prisma/prisma.yml
    extensions:
      codegen:
        generates:
          ./src/generated/prisma.graphql:
            plugins:
              - schema-ast